In [1]:
from langchain_openai import OpenAIEmbeddings
from graphdatascience import GraphDataScience
from getpass import getpass
import pandas as pd
import os
import numpy as np
import nltk
from nltk.stem import PorterStemmer
from IPython.display import display

/Users/nathansmith/anaconda3/envs/chatbot/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


# Set up connection to Neo4j

In [2]:
neo4j_password = getpass()

 ········


In [180]:
openai_api_key = getpass()

 ········


In [3]:
neo4j_uri = "neo4j+s://2fe3bf28.databases.neo4j.io"
neo4j_user = "neo4j"
gds = GraphDataScience(neo4j_uri, auth=(neo4j_user, neo4j_password))

# Find themes with common stems

In [303]:
nltk.download("punkt")

ps = PorterStemmer()

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/nathansmith/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [304]:
theme_df = gds.run_cypher("""MATCH (t:Theme) RETURN t.description AS description""")

In [305]:
theme_df['stem'] = theme_df['description'].map(lambda x: ps.stem(x))

In [306]:
grouped_themes = theme_df.groupby('stem').apply(np.unique, include_groups=False)

In [307]:
shared_stems = grouped_themes[grouped_themes.map(len)>1]
shared_stems_df = shared_stems.reset_index()
shared_stems_df.columns = ['stem', 'descriptions']
shared_stems_df.shape

(2646, 2)

In [308]:
shared_stems_df.sample(10)

stem                   descriptions
2049      scaveng        [Scavenger, scavengers]
314       carpent        [Carpenters, carpenter]
2050      sceneri           [sceneries, scenery]
295     camera fe    [camera feed, camera feeds]
680    doppelgäng  [Doppelgängers, doppelgänger]
599        denial              [denial, denials]
259    broken hom    [broken home, broken homes]
2454        twist       [twist, twisted, twists]
179          bell                  [Bell, Bells]
322   caterpillar    [Caterpillars, caterpillar]

## Send stems shared by multiple themes to Neo4j

In [310]:
gds.run_cypher("""CREATE CONSTRAINT stem_node_key IF NOT EXISTS FOR (s:Stem) REQUIRE s.stem IS NODE KEY""")

Empty DataFrame
Columns: []
Index: []

In [311]:
gds.run_cypher("""UNWIND $data AS row
MERGE (s:Stem {stem:row['stem']})
WITH row, s
UNWIND row['descriptions'] AS description
MATCH (t:Theme {description:description})
MERGE (t)-[:HAS_STEM]->(s)
SET s.descriptions = row['descriptions']
RETURN count(*) AS stemmedCount""",
              {"data": shared_stems_df.to_dict("records")})

stemmedCount
0          5767

## Aggregate theme vectors for themes that share a stem

In [312]:
shared_stem_df = gds.run_cypher("""
MATCH (s:Stem)<-[:HAS_STEM]-(t)
RETURN s.stem AS stem, collect(t.embedding) AS embeddings
""")

In [313]:
def get_mean_vector(row):
    mean_vector = np.array(row['embeddings']).mean(axis=0).tolist()
    return mean_vector

In [314]:
shared_stem_df['mean_embedding'] = shared_stem_df.apply(get_mean_vector, axis=1)

In [315]:
gds.run_cypher("""
    UNWIND $data AS row
    MATCH (s:Stem {stem: row['stem']})
    CALL db.create.setNodeVectorProperty(s, "meanEmbedding", row['mean_embedding'])""",
                   {"data":shared_stem_df[['stem', 'mean_embedding']].to_dict("records")})


Empty DataFrame
Columns: []
Index: []

# Create projection
Include stems and individual themes that do not share a stem with another theme.

Use the theme embedding and the aggregated embedding for stems.

In [487]:
g_themes, result = gds.graph.cypher.project("""
MATCH (t:Stem|Theme)
WHERE NOT EXISTS {(t)-[:HAS_STEM]->()}
RETURN gds.graph.project("themes", 
t, null,
{sourceNodeProperties: {embedding: CASE WHEN t:Stem then t.meanEmbedding ELSE t.embedding END},
targetNodeProperties: null}
)""")

Failed to write data to connection ResolvedIPv4Address(('34.28.32.244', 7687)) (ResolvedIPv4Address(('34.28.32.244', 7687)))
Failed to write data to connection IPv4Address(('2fe3bf28.databases.neo4j.io', 7687)) (ResolvedIPv4Address(('34.28.32.244', 7687)))


In [488]:
result

{'relationshipCount': 0,
 'graphName': 'themes',
 'query': '\nMATCH (t:Stem|Theme)\nWHERE NOT EXISTS {(t)-[:HAS_STEM]->()}\nRETURN gds.graph.project(******, \nt, ******,\n{sourceNodeProperties: {embedding: CASE WHEN t:Stem then t.meanEmbedding ELSE t.embedding END},\ntargetNodeProperties: ******}\n)',
 'projectMillis': 9561,
 'configuration': {'readConcurrency': 4,
  'undirectedRelationshipTypes': [],
  'jobId': 'd46f66fb-9cb8-4608-99b7-0a5dd3b1cbdf',
  'logProgress': True,
  'query': '\nMATCH (t:Stem|Theme)\nWHERE NOT EXISTS {(t)-[:HAS_STEM]->()}\nRETURN gds.graph.project(******, \nt, ******,\n{sourceNodeProperties: {embedding: CASE WHEN t:Stem then t.meanEmbedding ELSE t.embedding END},\ntargetNodeProperties: ******}\n)',
  'inverseIndexedRelationshipTypes': [],
  'creationTime': neo4j.time.DateTime(2024, 3, 22, 17, 56, 57, 945894861, tzinfo=<UTC>)},
 'nodeCount': 36970}

# Test some theme pairs to find a score above which you think themes are probably duplicated
Get a sense of the range of similarity values for top 5 nearest neighbors.

Note that KNN returns cosine similarity normalized to the range [0, 1]. 

If you run gds.similarity.cosine() you get similarity in the range [-1,1]

In [322]:
knn_stats = gds.knn.stats(g_themes, topK=5, nodeProperties = "embedding")

In [323]:
knn_stats['similarityDistribution']

{'min': 0.6269302368164062,
 'p5': 0.6885490417480469,
 'max': 0.9965553283691406,
 'p99': 0.9251556396484375,
 'p1': 0.6686859130859375,
 'p10': 0.7019996643066406,
 'p90': 0.86669921875,
 'p50': 0.7789230346679688,
 'p25': 0.7316360473632812,
 'p75': 0.8288040161132812,
 'p95': 0.8873481750488281,
 'mean': 0.7821673368743409,
 'p100': 0.9965553283691406,
 'stdDev': 0.06246581380926736}

## Given a theme, check to see how many neighbors are duplicates and the similarity score for the first neighbor you would consider to be a different theme.

db.index.vector.queryNodes() returns cosine similarity normalized to the range [0, 1]

In [331]:
top_k_df = gds.run_cypher("""
MATCH (t1:Theme) WHERE t1.description IN $themeList
CALL db.index.vector.queryNodes("theme_vectors", $k + 1, t1.embedding) YIELD node, score
WITH t1, node AS t2, score
WHERE t1 <> t2
RETURN t1.description AS theme1,
t2.description AS theme2,
score
ORDER BY theme1, score DESC""",
               {"k": 20,
                "themeList": ['friend', 'dance floor', 'Fast-food burger', 'guilt', 'antics', 
                              'ants', 'underwater', 'Africa', 'ChatGPT', 'coming-of-age']})

In [255]:
top_k_df[top_k_df['theme1'] == 'friend']
# top 4 cutoff 0.811518

theme1         theme2     score
120  friend       Friendly  0.825079
121  friend   friend group  0.823099
122  friend        friends  0.822041
123  friend     friendship  0.817366
124  friend  dream wedding  0.811518
125  friend           love  0.801542
126  friend        partner  0.799027
127  friend         family  0.797425
128  friend   dream mentor  0.795746
129  friend    friendships  0.792070
130  friend    dream child  0.788706
131  friend       siblings  0.788457
132  friend  friend or foe  0.787692
133  friend    true friend  0.785060
134  friend   relationship  0.784786
135  friend    dream venue  0.783656
136  friend       neighbor  0.781707
137  friend    best friend  0.779998
138  friend          mates  0.779471
139  friend  close friends  0.779305

In [256]:
top_k_df[top_k_df['theme1'] == 'dance floor']
# top 2 cutoff 0.876044

theme1              theme2     score
100  dance floor          Dancefloor  0.907340
101  dance floor         dance party  0.876044
102  dance floor         dance class  0.847459
103  dance floor          dance time  0.845335
104  dance floor      dance routines  0.844204
105  dance floor               dance  0.838422
106  dance floor        go-go dancer  0.837511
107  dance floor             dancing  0.837206
108  dance floor        dance studio  0.835570
109  dance floor        Step dancing  0.829465
110  dance floor       dance theater  0.825452
111  dance floor        school dance  0.821049
112  dance floor              dances  0.816844
113  dance floor        erotic dance  0.816773
114  dance floor         Dance music  0.816332
115  dance floor  dance performances  0.808826
116  dance floor              dancer  0.807537
117  dance floor         Grand dance  0.803678
118  dance floor          Dance diva  0.803300
119  dance floor        dance troupe  0.802784

In [257]:
top_k_df[top_k_df['theme1'] == 'Fast-food burger']
# top 4 cutoff 0.807412

theme1                theme2     score
40  Fast-food burger  fast food restaurant  0.854380
41  Fast-food burger             fast food  0.845039
42  Fast-food burger               burgers  0.825347
43  Fast-food burger           Burger Baby  0.810610
44  Fast-food burger         Vegan burgers  0.807412
45  Fast-food burger           Good Burger  0.800079
46  Fast-food burger            Burger van  0.780409
47  Fast-food burger          French fries  0.754924
48  Fast-food burger                burger  0.753647
49  Fast-food burger           street food  0.746388
50  Fast-food burger                   KFC  0.738850
51  Fast-food burger          crispy fries  0.733294
52  Fast-food burger       Subway sandwich  0.727122
53  Fast-food burger       Jack-in-the-Box  0.724755
54  Fast-food burger     McDonald Brothers  0.717698
55  Fast-food burger            french fry  0.717360
56  Fast-food burger         Food industry  0.717355
57  Fast-food burger        Roadside diner  0.717189
58  Fast-food burger     family restaurant  0.716436
59  Fast-food burger           snack shack  0.714168

In [258]:
top_k_df[top_k_df['theme1'] == 'guilt']
# top 6 cutoff 0.793735

theme1              theme2     score
140  guilt      Guilt and fear  0.822317
141  guilt  Guilt and paranoia  0.816934
142  guilt               blame  0.814373
143  guilt               shame  0.802213
144  guilt          self-blame  0.795776
145  guilt             remorse  0.795585
146  guilt             culprit  0.793735
147  guilt             accused  0.788248
148  guilt          conscience  0.778244
149  guilt      responsibility  0.768354
150  guilt              regret  0.763958
151  guilt           suspicion  0.763630
152  guilt          confession  0.758574
153  guilt          complicity  0.756750
154  guilt   Guilt-free future  0.756589
155  guilt    innocence doubts  0.755619
156  guilt                sins  0.754015
157  guilt    murder suspicion  0.753345
158  guilt          self-doubt  0.751299
159  guilt  survivor's remorse  0.749416

In [259]:
top_k_df[top_k_df['theme1'] == 'antics']
# top 0 cutoff 0.854217

Empty DataFrame
Columns: [theme1, theme2, score]
Index: []

In [330]:
top_k_df[top_k_df['theme1'] == 'ants']
# top 0 cutoff 0.854217

theme1     theme2     score
80   ants     antics  0.854217
81   ants     agents  0.851598
82   ants       rats  0.833571
83   ants      names  0.832501
84   ants       guns  0.828042
85   ants       webs  0.812752
86   ants        ads  0.807464
87   ants       pies  0.805520
88   ants     target  0.804613
89   ants     stocks  0.802675
90   ants      agent  0.799709
91   ants      homes  0.799397
92   ants      mates  0.798988
93   ants  mutations  0.797931
94   ants     things  0.794117
95   ants       crew  0.791735
96   ants    genesis  0.791265
97   ants    charges  0.789297
98   ants    choices  0.788970
99   ants        axe  0.787703

In [261]:
top_k_df[top_k_df['theme1'] == 'underwater']
# top 4 cutoff 0.880904

theme1                  theme2     score
160  underwater                undersea  0.946337
161  underwater              subaquatic  0.905288
162  underwater        underwater world  0.896511
163  underwater          undersea world  0.881089
164  underwater        underwater music  0.880904
165  underwater    underwater adventure  0.875346
166  underwater  underwater exploration  0.873639
167  underwater                deep sea  0.857809
168  underwater       underwater ballet  0.847281
169  underwater               submarine  0.846147
170  underwater       Underwater mining  0.836987
171  underwater              deep water  0.833938
172  underwater           Under the Sea  0.827439
173  underwater             deep waters  0.825337
174  underwater             Submersible  0.819398
175  underwater         Submerged world  0.817633
176  underwater             underground  0.809469
177  underwater            subterranean  0.798814
178  underwater       submerged village  0.794522
179  underwater           diving within  0.792122

In [262]:
top_k_df[top_k_df['theme1'] == 'Africa']
# top 0 cutoff 0.829958

theme1            theme2     score
0   Africa              Asia  0.829958
1   Africa            Europe  0.793405
2   Africa           African  0.792190
3   Africa          Atlantic  0.775041
4   Africa           America  0.765479
5   Africa             Asian  0.750807
6   Africa     African Union  0.750721
7   Africa       Pan-African  0.749782
8   Africa    African nation  0.748957
9   Africa    Horn of Africa  0.748596
10  Africa          Americas  0.741727
11  Africa     Trans-Saharan  0.740613
12  Africa         Australia  0.739899
13  Africa  authentic Africa  0.737925
14  Africa             Egypt  0.737744
15  Africa            Arabia  0.734646
16  Africa         Argentina  0.732920
17  Africa    African coasts  0.732280
18  Africa          European  0.732225
19  Africa         Alexander  0.729888

In [263]:
top_k_df[top_k_df['theme1'] == 'ChatGPT']
# top 2 cutoff 0.718462

theme1             theme2     score
20  ChatGPT           Chat-GPT  0.951617
21  ChatGPT              GPT-3  0.816252
22  ChatGPT                  G  0.718462
23  ChatGPT                 CG  0.715920
24  ChatGPT           Hangouts  0.714553
25  ChatGPT             GeGeGe  0.713404
26  ChatGPT                CGI  0.706873
27  ChatGPT                GDR  0.705540
28  ChatGPT            genesis  0.704529
29  ChatGPT               SMGP  0.703914
30  ChatGPT           Gotchard  0.703377
31  ChatGPT                GUI  0.700710
32  ChatGPT          CGI gator  0.700513
33  ChatGPT                GCW  0.700090
34  ChatGPT  Classified gadget  0.699636
35  ChatGPT           Gameshow  0.698899
36  ChatGPT               game  0.697707
37  ChatGPT                KGB  0.696868
38  ChatGPT              group  0.696759
39  ChatGPT     Global Probing  0.696026

In [334]:
top_k_df[top_k_df['theme1'] == 'coming-of-age']
# top 5 cutoff 0.791164

theme1                   theme2     score
100  coming-of-age            coming of age  0.980575
101  coming-of-age              adolescence  0.819819
102  coming-of-age               Growing-up  0.819564
103  coming-of-age                  puberty  0.802797
104  coming-of-age               growing up  0.799015
105  coming-of-age         post-adolescence  0.791164
106  coming-of-age                  boyhood  0.790140
107  coming-of-age               lost youth  0.770246
108  coming-of-age       youthful adventure  0.765915
109  coming-of-age  Transition to adulthood  0.763636
110  coming-of-age            teenage angst  0.763489
111  coming-of-age       broken adolescence  0.761357
112  coming-of-age            youth romance  0.759577
113  coming-of-age     teenage protagonists  0.756425
114  coming-of-age           teenage dramas  0.755379
115  coming-of-age         youthful romance  0.754938
116  coming-of-age               young love  0.754369
117  coming-of-age        young protagonist  0.754020
118  coming-of-age        Teenage adventure  0.752683
119  coming-of-age                    youth  0.752511

# Based on the exploration above run KNN with a similarityCutoff you choose

In [490]:
similarity_cutoff = 0.811518

knn_result = gds.knn.mutate(g_themes,
                            mutateRelationshipType = "IS_SIMILAR",
                            mutateProperty = "similarity",
                            nodeProperties = "embedding",
                            topK = 4,
                            sampleRate = 1.0,
                            perturbationRate = 0.5,
                            deltaThreshold = 0.00001,
                            similarityCutoff = similarity_cutoff)

## Find themes that discovered no neighbors above the similarity threshold you selected

In [ ]:
no_sim_df = gds.run_cypher("""
CALL gds.graph.relationships.stream("themes", ["IS_SIMILAR"]) yield sourceNodeId, targetNodeId
UNWIND [gds.util.asNode(sourceNodeId), gds.util.asNode(targetNodeId)] AS nodeWithSim
WITH collect(DISTINCT nodeWithSim) AS nodesWithSim
MATCH (t:Theme) WHERE NOT t IN nodesWithSim
AND NOT EXISTS {(t)-[:HAS_STEM]->()}
RETURN t.description AS description, count{ (t)<-[:HAS_THEME]-() } AS movieCount
ORDER BY movieCount desc""")

It's weird that "coming of age" shows up here, when we know that it has neghbor "coming-of-age" with score 0.980575 from the analysis above. KNN is using approximate nearest neighbors, and even with a sample rate of 1.0 it can miss some possible matches.

In [405]:
no_sim_df

description  movieCount
0        coming of age          71
1              poverty          55
2               London          54
3             paranoia          52
4            wrestling          51
...                ...         ...
16587            sauce           1
16588          saudade           1
16589    sausage rolls           1
16590   saving history           1
16591  saving humanity           1

[16592 rows x 2 columns]

In [406]:
no_sim_df[no_sim_df['movieCount'] > 1]['description'].count()

2174

## Examine theme pairs for high degree nodes
For Stem nodes, turn their list of descriptions into a comma separated string before exporting.

In [407]:
similarity_result = gds.run_cypher("""
    CALL gds.graph.relationshipProperty.stream("themes", "similarity", ["IS_SIMILAR"])
    YIELD sourceNodeId, targetNodeId, propertyValue AS similarity
    WITH gds.util.asNode(sourceNodeId) AS source, gds.util.asNode(targetNodeId) AS target, similarity
    RETURN coalesce(source.description, reduce(s = source.descriptions[0], d in source.descriptions[1..] | s + ", " + d)) AS source, 
    coalesce(target.description, reduce(s = target.descriptions[0], d in target.descriptions[1..] | s + ", " + d)) AS target, similarity
    ORDER BY similarity""")
                    

What are the nodes with the most inbound IS_SIMILAR relationships?

In [408]:
similarity_result.groupby("target")['source'].count().sort_values(ascending=False).head(20)

target
Humanism, Humanities, human, humanity, humanization, humans    39
haunted house, haunted houses                                  39
dark place                                                     37
acting dreams                                                  37
dream, dreaming, dreams                                        36
Musically, music, musical, musicals                            35
dance, dances, dancing                                         35
hidden secrets                                                 34
Rural community, rural communities                             33
LGBTQ+                                                         32
heartfelt stories                                              30
Wild journey                                                   29
Hauntings, haunt, haunted, haunting                            29
ordinary life                                                  29
human condition                                                28
eld

In [409]:
similarity_result[similarity_result['target']=="haunted house, haunted houses"]

source                         target  \
8892                       school haunting  haunted house, haunted houses   
10899                    haunted letterbox  haunted house, haunted houses   
12158                      haunted promise  haunted house, haunted houses   
12334                         haunted doll  haunted house, haunted houses   
15657                      haunted hairpin  haunted house, haunted houses   
17512                       haunted coffee  haunted house, haunted houses   
18009                    haunted childhood  haunted house, haunted houses   
23221                        haunted phone  haunted house, haunted houses   
24694                      haunted shadows  haunted house, haunted houses   
28595                       haunted photos  haunted house, haunted houses   
29397                    haunted classroom  haunted house, haunted houses   
30354                       haunted circus  haunted house, haunted houses   
30490                    haunted community  haunted house, haunted houses   
31418                    haunted imaginary  haunted house, haunted houses   
33037                        haunted tales  haunted house, haunted houses   
35603                         haunted book  haunted house, haunted houses   
36013                       haunted island  haunted house, haunted houses   
36890                        haunted spots  haunted house, haunted houses   
36914                          haunted box  haunted house, haunted houses   
37886                       Haunted places  haunted house, haunted houses   
39931                       haunted forest  haunted house, haunted houses   
40929                       haunted school  haunted house, haunted houses   
40977                      haunted theatre  haunted house, haunted houses   
41928                       haunted church  haunted house, haunted houses   
43031                    haunted apartment  haunted house, haunted houses   
43115                     haunted bungalow  haunted house, haunted houses   
45624                          haunted inn  haunted house, haunted houses   
46301                         haunted town  haunted house, haunted houses   
47143                   haunted guesthouse  haunted house, haunted houses   
47260                       haunted museum  haunted house, haunted houses   
47657                     haunted hospital  haunted house, haunted houses   
48405                        haunted villa  haunted house, haunted houses   
48672                      Unhaunted house  haunted house, haunted houses   
49337  Hauntings, haunt, haunted, haunting  haunted house, haunted houses   
50110                   haunted properties  haunted house, haunted houses   
50987                        haunted hotel  haunted house, haunted houses   
51021                       haunted estate  haunted house, haunted houses   
52086                     haunted building  haunted house, haunted houses   
53578                      haunted mansion  haunted house, haunted houses   

       similarity  
8892     0.823204  
10899    0.825859  
12158    0.827624  
12334    0.827866  
15657    0.832387  
17512    0.835167  
18009    0.835853  
23221    0.843519  
24694    0.845714  
28595    0.851900  
29397    0.853246  
30354    0.854881  
30490    0.855149  
31418    0.856788  
33037    0.859683  
35603    0.864266  
36013    0.865019  
36890    0.866800  
36914    0.866852  
37886    0.868877  
39931    0.873219  
40929    0.875369  
40977    0.875473  
41928    0.877811  
43031    0.880526  
43115    0.880735  
45624    0.887930  
46301    0.890221  
47143    0.893174  
47260    0.893598  
47657    0.895101  
48405    0.898173  
48672    0.899258  
49337    0.902352  
50110    0.906062  
50987    0.911147  
51021    0.911376  
52086    0.919657  
53578    0.939381

In [410]:
similarity_result[similarity_result['target']=="Humanism, Humanities, human, humanity, humanization, humans"]

source  \
786                     Humanity's rebirth   
3167                       humanized image   
4104                            human bond   
8113                    humanity's anxiety   
9095                 humanity's resistance   
9301                          human vision   
10864                 humanity's brutality   
12325                           post-human   
12429                               Humano   
12960                    Humanity's future   
12974                 Human exceptionalism   
16035                           human face   
20233                  humanity's survival   
20320        Human emotion, human emotions   
21795                      human curiosity   
22307                         human-animal   
22586                          Human lives   
25433                         human psyche   
26358                    human documentary   
27441                    human interaction   
27474                           good human   
29131                 Human Responsibility   
30963                              inhuman   
31362                  human relationships   
32404                      shared humanity   
35181                              Humanly   
35318                    human development   
37471                      human potential   
37738                      human existence   
39401                        human dignity   
39472                           human race   
40074                   human intelligence   
40362                 Humanist, Humanistic   
42793                          human value   
43422  human connection, human connections   
46224                          human world   
48599                         human nature   
48805                         Human beings   
52248                      human condition   

                                                            target  similarity  
786    Humanism, Humanities, human, humanity, humanization, humans    0.812533  
3167   Humanism, Humanities, human, humanity, humanization, humans    0.815523  
4104   Humanism, Humanities, human, humanity, humanization, humans    0.816853  
8113   Humanism, Humanities, human, humanity, humanization, humans    0.822183  
9095   Humanism, Humanities, human, humanity, humanization, humans    0.823478  
9301   Humanism, Humanities, human, humanity, humanization, humans    0.823740  
10864  Humanism, Humanities, human, humanity, humanization, humans    0.825814  
12325  Humanism, Humanities, human, humanity, humanization, humans    0.827854  
12429  Humanism, Humanities, human, humanity, humanization, humans    0.827981  
12960  Humanism, Humanities, human, humanity, humanization, humans    0.828705  
12974  Humanism, Humanities, human, humanity, humanization, humans    0.828730  
16035  Humanism, Humanities, human, humanity, humanization, humans    0.832960  
20233  Humanism, Humanities, human, humanity, humanization, humans    0.839022  
20320  Humanism, Humanities, human, humanity, humanization, humans    0.839169  
21795  Humanism, Humanities, human, humanity, humanization, humans    0.841381  
22307  Humanism, Humanities, human, humanity, humanization, humans    0.842174  
22586  Humanism, Humanities, human, humanity, humanization, humans    0.842577  
25433  Humanism, Humanities, human, humanity, humanization, humans    0.846715  
26358  Humanism, Humanities, human, humanity, humanization, humans    0.848192  
27441  Humanism, Humanities, human, humanity, humanization, humans    0.849904  
27474  Humanism, Humanities, human, humanity, humanization, humans    0.849963  
29131  Humanism, Humanities, human, humanity, humanization, humans    0.852782  
30963  Humanism, Humanities, human, humanity, humanization, humans    0.855977  
31362  Humanism, Humanities, human, humanity, humanization, humans    0.856685  
32404  Humanism, Humanities, human, humanity, humanization, humans    0.858525  
35181  Humanism, Humanities, human, humanity, humanization, humans    0.863523  
35318  H

In [411]:
similarity_result[similarity_result['target']=="Christmas magic"]

source           target  \
1480                              Christmas sweaters  Christmas magic   
5602                                 spicy Christmas  Christmas magic   
7388                                 Christmas curse  Christmas magic   
20353                                White Christmas  Christmas magic   
21500                                Christmas World  Christmas magic   
34402                                Christmas story  Christmas magic   
38776                               Christmas lights  Christmas magic   
38860                              Christmas Variety  Christmas magic   
40547                             Christmas memories  Christmas magic   
40860                                           Xmas  Christmas magic   
41151                              Christmas mystery  Christmas magic   
41977                                  Christmas eve  Christmas magic   
43455                                      christmas  Christmas magic   
44884                             Christmas ambience  Christmas magic   
46580                            Christmas nightmare  Christmas magic   
48821                                Christmas movie  Christmas magic   
49807                                Christmas break  Christmas magic   
50124                          Christmas decorations  Christmas magic   
50709                              Christmas miracle  Christmas magic   
51379                                Christmas party  Christmas magic   
52489                                  holiday magic  Christmas magic   
52503  Christmas celebration, Christmas celebrations  Christmas magic   
52613                               Christmas terror  Christmas magic   
52996                                 Christmas love  Christmas magic   
54054                               Christmas spirit  Christmas magic   

       similarity  
1480     0.813443  
5602     0.818920  
7388     0.821274  
20353    0.839211  
21500    0.840920  
34402    0.862150  
38776    0.870777  
38860    0.870974  
40547    0.874529  
40860    0.875206  
41151    0.875824  
41977    0.877892  
43455    0.881683  
44884    0.885654  
46580    0.891061  
48821    0.899849  
49807    0.904421  
50124    0.906152  
50709    0.909508  
51379    0.913629  
52489    0.923435  
52503    0.923514  
52613    0.924765  
52996    0.929875  
54054    0.952886

In [412]:
similarity_result[similarity_result['target']=="documentary video"]

source             target  \
2144                               music documentary  documentary video   
2290                                 DIY Documentary  documentary video   
8422                          generative documentary  documentary video   
14119                          revealing documentary  documentary video   
17467                             social documentary  documentary video   
22154                         documentary confession  documentary video   
28017                                    Dogumentary  documentary video   
28775                          Political documentary  documentary video   
35271                               fake documentary  documentary video   
36881                           animated documentary  documentary video   
36981                              documentary fable  documentary video   
43373                               documentary crew  documentary video   
44116                        documentary exploration  documentary video   
48546                            Documentary Footage  documentary video   
49715                         documentary interviews  documentary video   
50894                             documentary series  documentary video   
51883                              documentary-style  documentary video   
52861                              documentary essay  documentary video   
53066  documentary filmmaker, documentary filmmaking  documentary video   
53538                     documentaries, documentary  documentary video   
53985                               documentary film  documentary video   

       similarity  
2144     0.814246  
2290     0.814440  
8422     0.822653  
14119    0.830216  
17467    0.835099  
22154    0.841925  
28017    0.850870  
28775    0.852186  
35271    0.863661  
36881    0.866787  
36981    0.866983  
43373    0.881450  
44116    0.883641  
48546    0.898754  
49715    0.903989  
50894    0.910480  
51883    0.917704  
52861    0.927860  
53066    0.930675  
53538    0.938533  
53985    0.950835

# Write weakly connected components with threshold at your KNN similarityCutoff or a higher value

In [413]:
gds.wcc.write(g_themes,
              writeProperty = "wccId",
              relationshipTypes = ["IS_SIMILAR"],
              relationshipWeightProperty = "similarity",
              threshold = 0.875,
              minComponentSize=2)

writeMillis                                                                                                                                                                                                                                                                                                                                                                   107
nodePropertiesWritten                                                                                                                                                                                                                                                                                                                                                        7630
componentCount                                                                                                                                                                                                                                                      

## Examine the largest communities at the KNN value you selected

In [414]:
pd.set_option('display.max_colwidth', None)

In [415]:
gds.run_cypher("""
MATCH (t:Theme)
WHERE t.wccId IS NOT NULL
WITH t.wccId AS id, collect(t.description) AS themes
RETURN id, size(themes) AS themeCount, themes
ORDER BY themeCount DESC
LIMIT 30""")

id  themeCount  \
0    369         207   
1    357         138   
2    570         115   
3      1          99   
4    419          96   
5    437          77   
6     12          64   
7    971          64   
8     45          52   
9    953          46   
10  1853          45   
11   858          42   
12   596          41   
13  1125          41   
14   913          41   
15  1365          40   
16   608          35   
17  1107          34   
18  1397          33   
19  2198          33   
20   116          31   
21  1588          30   
22   617          30   
23   198          29   
24   187          29   
25   457          29   
26   210          27   
27  1004          27   
28   653          27   
29   209          27   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 themes  
0                              [Accidental discovery, Ancient lore, Blurring reality, Buried, Creepy Mansion, Darker truth, Disturbing presence, Enchanted forest, Enchanted garden, Enigmatic identity, Enigmatic origin, Enigmatic strangers, Fairy-tale land, Fairytale world, Fiction blurring reality, Fiction reality, Folktale, Forbidden passion, Green fairies, Haunted campus, Haunted carriage, Haunted chapel, Haunted cinema, Haunted hill, Haunted home, Haunted manor, Haunted market, Haunted mask, Haunted memories, Haunted palace, Haunted party, Haunted places, Haunted temple, Haunted theme park, Haunted train, Haunted well, Haunting visions, Hidden desire, Invisible realm, Monster mask, Mysterious Guy, Mysterious old man, Mysterious realm, Mysterious secrets, Mysterious woods, Mystical beast, Mystical beings, Mystical realm, Mythical being, Mythos, Past ghosts, Reality blurred, Secret Mansion, Secret Unravels, Secret passion, Secret uncovered, Secrets unraveling, Shadowy Legacy, Shadowy figure, Shady company, Shady organization, Startling revelations, Supernatural visions, Uncovered secrets, Unhaunted house, Winter fairy tale, air fairies, ancient mythology, another realm, blurred reality, buried alive, buried body, buried dreams, buried history, buried skeleton, buried truth, buried wish, concealed truth, concealing truth, dark history, dark truth, disembodied spirit, dreams vs reality, enchanted world, enigmatic, enigmatic figure, enigmatic past, enigmatic woman, fairy-tale, fairytale characters, fantastical world, fantasy land, fantasy reality,

# Create undirected graph for Leiden

The largest WCC communities are too big. For example, "enchanted forest" and "buried body" do not belog in the same community. We'll use Leiden to make smaller comminities.

Leiden requires undirected relationships, so convert the directed IS_SIMILAR relationship to an undirected relationship called "UNDIRECTED_SIMILAR".

In [491]:
gds.run_cypher("""
call gds.graph.relationships.toUndirected("themes", {relationshipType: "IS_SIMILAR", mutateRelationshipType: "UNDIRECTED_SIMILAR", aggregation: "MAX"})""")

inputRelationships  relationshipsWritten  mutateMillis  \
0               53686                 71200             0   

   postProcessingMillis  preProcessingMillis  computeMillis  \
0                     0                    0             97   

                                                                                                                                                                                                     configuration  
0  {'aggregation': 'MAX', 'relationshipType': 'IS_SIMILAR', 'jobId': '7644d61d-1bc9-45ed-8df8-4a438c62b76c', 'logProgress': True, 'concurrency': 4, 'sudo': False, 'mutateRelationshipType': 'UNDIRECTED_SIMILAR'}

## Transform relationship weights
Because of our similarity cutoff in KNN, all of our relationship scores are between 0.811518 and 1.0. Apply a transformation to spread them out between 0.0 and 1.0.

In [492]:
gds.set_database("neo4j")

In [493]:
gds.run_cypher("""
CALL gds.graph.relationshipProperties.stream($graphName, ["similarity"], ["UNDIRECTED_SIMILAR"])
YIELD sourceNodeId, targetNodeId, propertyValue
WITH sourceNodeId AS source, 
targetNodeId AS target,
max(propertyValue) AS score
WITH gds.graph.project("reweight_themes",
source,
target,
{relationshipType: "IS_SIMILAR",
relationshipProperties: {similarity: (score-$similarityCutoff)/(1-$similarityCutoff)}},
{undirectedRelationshipTypes: ["IS_SIMILAR"]}) AS g
RETURN g.graphName AS graphName, g.relationshipCount AS relationshipCount, g.nodeCount AS nodeCount""",
              {"graphName": g_themes.name(), "similarityCutoff": similarity_cutoff})

graphName  relationshipCount  nodeCount
0  reweight_themes             142400      19473

In [494]:
g_themes2 = gds.graph.get("reweight_themes")

# Test Leiden with different values of gamma
This function will run the Leiden algorithm with a value of gamma that you provide. It will return the size of the biggest Leiden communities and the themes in those communities. It will also check for the smallest communities that contain only one document.

In [500]:
def test_leiden_gamma(gamma):
    property_name = f"leidenGamma{gamma}"
    try:
        gds.graph.nodeProperties.drop(g_themes2, property_name)
    except:
        pass
    leiden_result = gds.leiden.mutate(g_themes2,
                      mutateProperty = property_name,
                      relationshipTypes = ["IS_SIMILAR"],
                      relationshipWeightProperty = "similarity",
                      gamma=gamma)
    biggest_communities = gds.run_cypher("""
        CALL gds.graph.nodeProperty.stream("reweight_themes", $propName)
        YIELD nodeId, propertyValue
        WITH propertyValue, collect(gds.util.asNode(nodeId)) AS nodeList, count(*) as themeCount
        ORDER BY themeCount desc
        LIMIT 20
        RETURN themeCount, [n in nodeList | coalesce(n.description, n.descriptions)] AS themes""",
                                        {"propName": property_name})
    stats_df = gds.run_cypher("""
        CALL gds.graph.nodeProperty.stream("reweight_themes", "leidenGamma1.0")
        YIELD nodeId, propertyValue
        WITH gds.util.asNode(nodeId) as n, propertyValue AS leidenId
        WITH leidenId, collect(n) AS nodeList
        WHERE size(nodeList) = 1
        WITH leidenId, nodeList[0] AS n
        WITH leidenId,
        COUNT{MATCH (n)<-[:HAS_THEME]-(d) RETURN DISTINCT d} AS themeCount,
        COUNT{MATCH (n)<-[:HAS_STEM]-()<-[:HAS_THEME]-(d) RETURN DISTINCT d} AS stemCount
        WHERE themeCount + stemCount = 1
        RETURN count(*) AS singleDocCommunities""",
                                           {"propName": property_name})
    stats_df.loc[0,'community_count'] = leiden_result['communityCount']
    stats_df.loc[0, 'max_community_size'] = leiden_result['communityDistribution']['max']
    stats_df.loc[0, 'mean_community_size'] = leiden_result['communityDistribution']['mean']
    stats_df.loc[0, 'median_community_size'] = leiden_result['communityDistribution']['p50']
    stats_df.loc[0, 'gamma'] = gamma
    return {"biggest_communities": biggest_communities, "stats": stats_df}
                                           


In [504]:
gamma_tests = {gamma: test_leiden_gamma(gamma) for gamma in [1.0, 2.0, 4.0, 8.0, 16.0, 32.0, 64.0, 128.0, 256.0, 512.0, 1024.0]}

In [509]:
stats_df = pd.concat([r['stats'] for r in [gamma_tests[key] for key in gamma_tests.keys()]])
stats_df[['gamma', 'singleDocCommunities', 'community_count', 'max_community_size', 'mean_community_size', 'median_community_size']]

gamma  singleDocCommunities  community_count  max_community_size  \
0     1.0                     0           1644.0               430.0   
0     2.0                     0           1705.0               282.0   
0     4.0                     0           1792.0               218.0   
0     8.0                     0           1910.0               145.0   
0    16.0                     0           2071.0               134.0   
0    32.0                     0           2254.0                71.0   
0    64.0                     0           2524.0                53.0   
0   128.0                     0           2871.0                39.0   
0   256.0                     0           3369.0                27.0   
0   512.0                     0           4152.0                20.0   
0  1024.0                     0           5420.0                15.0   

   mean_community_size  median_community_size  
0            11.844891                    2.0  
0            11.421114                    2.0  
0            10.866629                    2.0  
0            10.195288                    2.0  
0             9.402704                    2.0  
0             8.639308                    3.0  
0             7.715135                    3.0  
0             6.782654                    3.0  
0             5.780053                    4.0  
0             4.690029                    4.0  
0             3.592804                    3.0

In [511]:
for gamma, result in gamma_tests.items():
    print(f"Gamma value: {gamma}")
    display(result['biggest_communities'].head())

Gamma value: 1.0


themeCount  \
0         430   
1         382   
2         344   
3         316   
4         307   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              themes  
0  [strange phenomenon, phenomenon, strange artifact, strange phenomena, Mysterious phenomenon, Bizarre phenomena, phenomena, strange force, strange performance, [strange event, strange events], dark stories, Scary Tales, Gripping tales, terrifying tales, Killer tales, haunted tales, [twisted tale, twisted tales], strange man, strange woman, strange couple, Strange man's house, weird guy, strange owner, strange figure, strange proposal, strange person, strange bird, strange, bleak stories, Legendary tales, supernatural tales, Halloween disappearance, Natural phenomenon, enigmatic, enigmatic key, enigmatic castle, enigmatic figure, enigmatic event, enigmatic patron, enigmatic feelings, enigmatic plot, enigmatic woman, enigmatic past, [Elusiveness, elusive], [Enigmas, enigma], mysterious woman, mystery woman, mysterious man, mysterious women, mysterious object, mysterious body, mysterious entity, mysterious ship, Strange abilities, Strange happenings, Strange situations, [Strange occurrence, strange occurrences], charisma, [charm, charming], Uncommon love, unconventional love, Unusual love, Uncommon name, unusual help, Unusual occurrence, Unusual Case, unusual solution, [unusual method, unusual methods], strange object, [stranger, strangers], Absurd encounters, surreal encounters, [strange encounter, strange encounters], Quirky acquaintance, Eccentric stranger, unconventional theories, Unconventional, unconventional teaching, unorthodox science, unconventional choices, [Unconventional relationships, unconventional relationship], Unconventional life, terrible act, Terrible tragedy, Heinous act, terrible situation, Horrific crime, colorless world, Colourless, wild creatures, native animals, hidden creatures, saving creature, creatures flee, invisible creatures, forest creatures, wildlife, [creature, creatures], Freaky world, Frightening world, ...]  
1                       [patriarch, Patriarchal norms, matriarch, mother-child relationship, mother's love, mother-son relationship, mother-da

Gamma value: 2.0


themeCount  \
0         282   
1         241   
2         233   
3         213   
4         206   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                themes  
0                                                                                                                                                  [ski-movie, ski film, Cinematic sketches, Cinematic essay, Filmmaker's aesthetics, Filmmaker persona, Filmmaker's project, filmmaker's perspective, Filmmaker fragments, [Experimental filmmaking, experimental filmmaker, experimental filmmakers], stag films, art film, handcrafted film, artist film, artistic cinema, concert film, artistic film circles, unfinished film, paint on film, touching film, [Experimental films, experimental film], Action star, Movie man, movies within movies, movie props, handmade, handcrafted filmmaking, anime film, Anime world, anime-inspired, action film, screenplay, screenplay scenes, roleplay, [film, filming, films], [show, shows], Italian Filmmaker, Audacious filmmaker, Bipolar filmmaker, Dedicated filmmaker, filmmaker relationship, filmmaker couple, Filmmaker's Notebook, Movie set, Movie project, On set, movie production, cinematic history, Cinematographic origin, cinematic passion, cinematic journey, cinema history, cinematic world, cinematic, cinematic universe, cinematic knowledge, cinematic image, cinematic future, film grain, film frames, Cannes festival, Cannes Film Festival, [Film festival, film festivals], Travelling cinema, Expanded cinema, aspiring screenwriter, Screenwriting professor, filmmaking aspirations, aspiring filmmaker, Film actor, Film hero, popular movie, movie about movie, movie lovers, Film archive, Film collector, film artifacts, film institution, Cinema closures, cinema's future, cinema outing, cinema business, [Cinemas, cinema], Cinema evolution, Cinema pioneer, Cinema Odyssey, Movie premiere, Film promotion, Premiere day, movie reception, premiere, Personal film, Home film, Role search, Roles, [role-play, role-playing], [student film, student films], flickering visuals, flicker film, flickering tracings, ...]  
1         

Gamma value: 4.0


themeCount  \
0         218   
1         191   
2         182   
3         175   
4         162   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            themes  
0                                                                                                                                                                                                                                                                                                         [ski-movie, ski film, Filmmaker's aesthetics, Filmmaker persona, Filmmaker's project, filmmaker's perspective, Filmmaker fragments, [Experimental filmmaking, experimental filmmaker, experimental filmmakers], stag films, art film, handcrafted film, artist film, artistic cinema, concert film, artistic film circles, unfinished film, paint on film, touching film, [Experimental films, experimental film], Action star, Movie man, movies within movies, movie props, handmade, handcrafted filmmaking, anime film, Anime world, anime-inspired, action film, screenplay, screenplay scenes, roleplay, [film, filming, films], [show, shows], Italian Filmmaker, Audacious filmmaker, Bipolar filmmaker, Dedicated filmmaker, filmmaker relationship, filmmaker couple, Filmmaker's Notebook, Movie set, Movie project, On set, movie production, film grain, film frames, Travelling cinema, Expanded cinema, aspiring screenwriter, Screenwriting professor, filmmaking aspirations, aspiring filmmaker, Film actor, Film hero, popular movie, movie about movie, movie lovers, Film archive, Film collector, film artifacts, film institution, Movie premiere, Film promotion, Premiere day, movie reception, premiere, Personal film, Home film, Role search, Roles, [role-play, role-playing], [student film, student films], flickering visuals, flicker film, flickering tracings, Crime movies, movie idea, Film challenge, [Film project, Film projection], [filmmaker, filmmakers, filmmaking], Avant-garde cinema, imaginary cinema, Dadai

Gamma value: 8.0


themeCount  \
0         145   
1         136   
2         129   
3         122   
4         120   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        themes  
0           [family wound, Family baggage, Family mystery, Family inheritance, Family power, family heritage, family dysfunction, family opposition, family disruption, family suffering, dysfunctional family, family stability, family fracture, family decay, family dynamics, [family conflict, family conflicts], [family struggle, family struggles], familial bonds, family ties, familial relationships, [Family bond, family bonding, family bonds], family unity, family love, family values, family honor, family vs duty, family duty, inherited knowledge, [inheritance, inherited], poverty struggles, Economic struggles, Family obligations, Family fragments, family reunion, family memory, family roots, family relationships, [family tension, family tensions], Salted feud, family feud, Family antics, Family interference, Family rift, Family strife, family fun, [family gathering, family gatherings], Powerful Family, family land, family home, Family healing, Family survival, Family creation, Family conversations, Family story, [family secret, family secrets], young family, family denial, family reluctance, family curse, family dynasty, family succession, family legacy, family wedding, family business, family estate, family move, family visit, familial tensions, personal tensions, Christmas reunion, family investigation, family reconciliation, family drama, Family Importance, Family crime, family influence, family spell, Family culture, Family and career, family history, heritage, family heirloom, family legend, [family archive, family archives], [legacies, legacy], [family agency, family agents], family threat, Family pain, Family impact, family turmoil, family terror, [family pressure, family pressures], family life, family harmony, family man, traditional family, [families, family], family safety, family protection, family dignity, ...]  
1                                                                                                                                   [artistic expression, expressive power, [expression, e

Gamma value: 16.0


themeCount  \
0         134   
1         111   
2         103   
3          98   
4          89   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          themes  
0                                                                                                                                                                                       [artistic expression, artistic movement, art form, artistic struggle, art of movement, artistic life, Art degree, Art critic, Art history, Fine Arts, art teacher, [Art school, art schools], [art student, art students], art scene, Art events, art world, Art space, art circles, art struggle, [art, arte], art clash, visual art, artist accused, visual artist, [artist, artistic, artists], artist's journey, artistic journey, poetic journey, artist's struggle, [artistic process, artistic processes], [Aspiring artist, Aspiring artists], Poetic Narrative, Poetic imagery, Mosaic narrative, Unexpected inspiration, artistic inspiration, Contemporary composition, Contemporary context, contemporary styles, contemporary art, Berlin artist, art collector, art lovers, modern art, new art form, Abstract art, Modern architecture, Pop art, artistic talent, Artistic integrity, artistic freedom, Artistic passion, artistic work, artistic recognition, Art installation, Experimental art, art exhibition, performance art, Interactive art, Artwork, art project, artistic vision, artistic ambition, poetic visions, musical legacy, Musical revolution, cultural legacy, artistic legacy, Aspiring illustrator, Animation pioneers, artistic obsession, Artistic dedication, artistic attitudes, artistry, Artifice, Brutalist architecture, art performance, Art theft, Art mystery, Art inspiration, [artistic career, artistic careers], art-based research, artistic ecology, creative art, Art devotion, Art therapy, Art Biennale, Saving Art, art gallery, Art world canon, [art dealer, art dealers], Unique talent, art over war, artistic muse, Artistic past, artistic haven, Conceptual art, kinetic art, body art, make art, ...]  
1  [ski-movie, ski film, Filmmaker's aesthetics, Filmmaker persona, Filmmaker's project, filmmaker's perspective, Film

Gamma value: 32.0


themeCount  \
0          71   
1          69   
2          69   
3          69   
4          64   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             themes  
0  [higher consciousness, consciousness, quantum consciousness, human consciousness, human development, human potential, human condition, human intelligence, [Humanism, Humanities, human, humanity, humanization, humans], Meat N' Sauce, Meat Cutes, meat, human subjects, [human experience, human experiments], Human atmospheres, [human connection, human connections], animal experimentation, Human exceptionalism, human perception, human vision, human value, human dignity, Human Responsibility, human spirit, [Humanist, Humanistic], human face, human nature, human soul, [human cost, human costs], human rights, Humanly, Human-android partnership, Human-dog relationships, Human-image relationship, human-animal, Being awareness, human meat, human-animal communication, Human-dog conflict, human curiosity, shared humanity, human existence, human race, human world, Human instincts, [Human emotion, human emotions], soul salvation, Soulism, [soul, soulful, souls], human creativity, Humanity's rebirth, human documentary, inhuman, good human, post-human, human impact, human activity, human interaction, human intervention, human memories, human motion, human relationships, Human lives, Meat & Greet, human bond, Intensely Soulful, Soul-collecting, Humano, non-human, Sweetmeats, hope for humanity]  
1                                  [boyfriend, twin brother, [brother, brothers], [sibling bond, sibling bonds], missing sister, Superhero twins, twins, relatives' lives, sibling's burden, sibling rivalry, sibling sacrifice, siblinghood, [sibling, siblings], sisterhood bonds, sisterhood, Female bonding, sisterly love, [sisterly bond, sisterly bonds], rival families, [Sibling relationships, sibling relationship], Donbrothers, rival dealership, rival teams, father-in-law, son-in-law, sister-in-law, brother-in-law, [mother-in-law, mother-in-laws], Brother boyfriend, Boyfriend Miguel, ex-boyfriend, Brother's inspiration, Brothers' mission, supportive brother, Devoted brother, Sisters' struggle, sorority, [sister, sisters], twin sisters, Sibling protection, Sibling contrasts, dead sister, brotherhood, fraternity, [Brotherly bonds, brotherly bond], Sisterly persuasion, Sibling visit, adopted sister, brother sister, Sister's death, deceased sister, pregnant sister, Missing sibling, younger sister, [Estranged sister, estranged sisters], [half-sister, half-sisters], homicidal sibling, Sibling Team, peculiar sisters, step brothers, brothers and sisters, Stepsiblings, brotherly love, sibling filmmakers, brother and sister, Step-relatives, brother Jacob, bros, [half-brother, half-brother

Gamma value: 64.0


themeCount  \
0          53   
1          52   
2          51   
3          50   
4          50   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              themes  
0                          [[horror stories, horror story], teen horror, teenage horror, J-horror, Deadly Horror, family horror, Real horror, historical horror, Television horror, Italian horror, body horror, Turkish horror, B-horror, [horror, horrors], [Horror filming, horror film, horror films], [Horror movies, horror movie], Horror series, neo-noir, noir, Horror-Noir, Comedy-Horror, Horror reboot, Horror homage, [Horror classic, horror classics], psycho-horror, horror-comedy, horror comedy, Horror icons, Horror elements, Horror villains, [Horror legend, horror legends], Bodily horror, real-life scary, Horror setting, Villains from Past, horror compilation, horror anthology, horror videos, horror footage, Horror games, horror convention, gothic horror, horror genre, Gothic romance, horror franchise, Found footage horror, horrific beings, horror realm, Horrorwood Saga, Fantastic genre, 70s Horror, 70s/80s horror, [B-movie, B-movies]]  
1                                                                                                                                                               [dark room, Dark realities, Unknown realities, Dark realm, dark thoughts, Darkness beneath, Darkness within, dark characters, inner darkness, dark place, out of darkness, dark world, lurking darkness, Darkness and silence, [dark, darkness], Dark Haven, dark web, dark network, Dark tale, Dark Prison, dark path, dark office, Dark Highway, [Dark Fantasy, dark fantasies], [Dark forests, dark forest], dark house, dark walls, dark road, dark themes, Deep dark, dark time, dark corridors, dark city, dark holes, dark tunnel, dark twist, dark abyss, dark scheme, [dark cloud, dark clouds], Darkness to light, dark journey, darkness vs. light, dark plot, impending invasion, impending doom, dark cracks, darkness looming, Dark Void, dark turn, darkest times, [Abyss, abyssal], [cloud, clouds]]  
2                                                                                        [Black imagination, Black stories, Black experience, Black culture, [Blackness, Blacks, black], Black icon, African village, Black actress, black woman, Black model, Black artist, black women, African American culture, African culture, African-American youth, [African American, African Americans], African, Black power, African drum, Drummer, African nation, African themes, Black farmers, Black neighborhoods, Black men, Black students, black workers, [Black musician, Black musicians], African Union, Black representation, Black struggle, non-white experience, White privilege, White people, black man, Underserved youth, Black beauty, Black British, Black teenager, People of color, Black folks, drums solo, black identities, [Black communities, Black community], Black boys, Black managers, Black Saint, black water, black ink, Pan-African, Black bodies]  
3                                                                                         [Cinem

Gamma value: 128.0


themeCount  \
0          39   
1          39   
2          39   
3          38   
4          37   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 themes  
0                                                                                                                                                                                                                                                                                                                                                                   [extraordinary life, ordinary lives, ordinary life, hidden lives, Wonderful life, beautiful life, routine life, domestic life, home life, teen life, normal life, little life, simple life, modest life, hidden life, structured life, repetitive life, traditional life, easy life, Life structure, Constructed life, Whole life, Stable Life, ordinary people, ordinary scenes, better life, simplicity, hard life, Passion for Life, One Life, Retirement life, PA life, van life, public life, short life, another life, perfect life, Normalcy, Life's secret]  
1  [Scientific expedition, Scientific investigation, Science experiment, Scientific Discovery, scientific experiment, scientific study, scientific research, Physics experiment, [experience, experiences, experiment, experimented, experimenting, experiments], [experimental, experimentation], scientific exploration, experimental exploration, scientific insights, experimental form, formal experiments, scientific responsibility, scientific facility, Experimental trial, Experimental treatment, Experimental punishment, Scientific ethics, research scientist, [research, researcher, researchers], sexual exploration, medical ethics, Research team, experiential investigation, thought experiment, experimental adaptation, Dual exploration, experimental research, exploring world, social experiment, sexual awakening, field research, Medical Research, medical studies, editing experiments, research interest]  
2                                                                                                                                                                                                                   [Monstrous transformation, monstrous inhabitants, forest monster, [swamp monster, swamp monsters], vile monsters, Undead monster, animatronic horrors, animated monsters, [alien monster, alien monsters], classic monsters, [monster, monsters], Miniature world, gargantuan, giant monster, [giant, giants], Sky monster, giant kraken, deformed monster, giant robots, Massive Monster, Behemoth, Naked giant, Monster within, Giant Girl, Monsternado, [Monstro, monstros], horrific beings, Monsters These Days, Monster-hunters, human monster, miniature monsters, Monster invasion, monster movie, small figure, [miniature, miniatures], MonsterVerse, Monster fetus, colorful monsters, Tiny Terror toys]  
3                                                                                                                                                                         [community center, community concern, speech therapy, Social Therapy, Community leaders, Community bonds, 

Gamma value: 256.0


themeCount  \
0          27   
1          26   
2          25   
3          25   
4          25   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           themes  
0  [human condition, human intelligence, [Humanism, Humanities, human, humanity, humanization, humans], Human exceptionalism, human perception, human vision, human spirit, [Humanist, Humanistic], human face, human nature, Humanly, human curiosity, shared humanity, human existence, human race, human world, Human instincts, [Human emotion, human emotions], human creativity, Humanity's rebirth, inhuman, good human, post-human, human motion, Human lives, Humano, hope for humanity]  
1                                                                                                                                       [Bread and Blood, Blood and tears, Blood conveyor, Blood trade, bloodshed, bloodlust, Blood shed, blood lust, blood ritual, Blood stains, Bleeds, blood pact, blood money, blood dreams, Lust for blood, blood path, blood, blood supply, blood room, Blood Red, bloodbath, Blood cult, bloodlines, blood-soaked nights, blood addiction, Accursed blood]  
2                    [Bureaucrats, [Civil servant, civil servants], riot police, IPS officer, police inspector, police chief, Indian police, police constable, Police captain, [police officer, police officers], law enforcement, Law enforcement accountability, [police, policing], policewoman, policeman, time police, Senior constable, [Constable, constables], Patrolman, Policeman neighbor, missing officer, service officer, Met Police, police force, [Police state, police station]]  
3                                                                            [romantic square, interracial romance, [romance, romances], wartime romance, romantic comedy, Romantic satire, Romantic thriller, romantic, rom-com, romantic action, romance novel, maritime romance, novelist, author's novel, novel, romance novelist, Steamy romance, Romantic love, bromance, [Romance scams, romance scam], unfinished novel, sailor romance, romantic language, romance king, romance writer]  
4                                                                                                                           [extraordinary life, ordinary lives, ordinary life, routine life, normal life, little life, simple life, modest life, structured life, repetitive life, traditional life, easy life, Life structure, Constructed life, Whole life, Stable Life, ordinary people, ordinary scenes, simplicity, hard life, Retirement life, PA life, public life, short life, Normalcy]

Gamma value: 512.0


themeCount  \
0          20   
1          18   
2          18   
3          17   
4          17   

                                                                                                                                                                                                                                                                                                                                                                      themes  
0                                                                    [Community chaos, police chaos, chaos, Collective disarray, Mass chaos, chaotic events, mayhem, havoc, home-brewed chaos, chaotic, order in chaos, chaotic world, chaos theory, Hilarious chaos, labyrinthine chaos, Chaotic poetry, chaotic lifestyle, chaotic response, erratic, Disrupted lifestyle]  
1                                                                                            [Sanctuary City, Sacred city, Sacred Path, Sacred place, sacred nature, sacred site, Sacred lake, pilgrimage site, sacred images, sacred, Sacred objects, sacred territory, indigenous territory, Holy Place, holy ground, meaningful images, special places, different places]  
2                                                                                       [child escape, Train escape, escape attempt, no escape, school escape, [Escapes, escape, escapism], clinic escape, escape routine, [escape plan, escape plans], Escaping war, mental escape, Great escape, mind escape, no way out, escape rooms, Escape pod, Trapped room, escapee]  
3  [Corporate competition, Corporate politics, Complex competition, [Tournaments, tournament], Stone bridge, [bridge, bridges], Cutthroat competition, Intense competition, competitive pursuit, [Competitions, competition, competitive], talent competition, ring competition, bridge competition, team competition, Academic competition, Talentshow, school talent show]  
4                                                                           [dance routines, dance performances, dance theater, dance vignettes, [dance, dances, dancing], [dancer, dancers], time's dance, cultural dances, Collective dance, [Drag performers, drag performer], dancing friends, Bailando, dance contests, vogue dancing, school dance, belly dance, Tanz]

Gamma value: 1024.0


themeCount  \
0          15   
1          14   
2          13   
3          13   
4          13   

                                                                                                                                                                                                                                                                                      themes  
0                                                               [Seaside village, beach house, Beachside getaway, beach setting, Paradise beach, Beach bar, beachbreak, The Beach, [beach, beaches], Beach romance, Beach reunion, Beach Punk, beach closure, beach vendors, The Beach Boys]  
1                                                                                   [River murder, river tragedy, River life, riverside, River Boy, riverine, River setting, River guides, [Flowing river, flowing rivers], [river, rivers], River Cam, waterways, Rivulet, [Flow, flowing]]  
2  [Amateur boxing, Amateur tournament, [Tournaments, tournament], Stone bridge, [bridge, bridges], Cutthroat competition, Intense competition, competitive pursuit, [Competitions, competition, competitive], ring competition, bridge competition, team competition, Academic competition]  
3                                                                  [Subjugated humanity, Suffering humanity, suffering, Physical suffering, patient suffering, Souffrir, Sufrimiento, Psychological suffering, physical pain, Physical ailment, silent pain, [pain, painful], Human anguish]  
4                                                 [feminist mayor, feminista, feminist initiative, feminist collective, Feminist media, Feminist filmmakers, Eco-feminist, feminist protest, feminist reimagining, [Feminisms, feminism], French feminist, Feminist themes, feminist sci-fi]

## For individual themes, see what other themes drop out of their communities as you increase gamma

In [438]:
def get_proprety_df(property_name):
    property_df = gds.graph.nodeProperties.stream(g_themes2,
                                                  [property_name],
                                                  db_node_properties = ["description", "descriptions"],
                                                  separate_property_columns=True)
    property_df.loc[pd.notna(property_df['descriptions']), 'descriptions'] = property_df.loc[pd.notna(property_df['descriptions']), 'descriptions'].map(lambda x: ", ".join(x))
    property_df['description'] = property_df.apply(lambda row: row['description'] if row['description'] else row['descriptions'], axis=1)
    property_df.drop('descriptions', axis=1, inplace=True)
    return property_df

property_dfs = {property_name: get_proprety_df(property_name)
                for property_name in [f"leidenGamma{gamma}" for gamma in [32.0, 64.0, 128.0, 256.0, 512.0, 1024.0]]}

In [439]:
def get_cluster_for_theme(property_name, theme):
    theme_df = property_dfs[property_name]
    result_list = [theme]
    if theme in theme_df['description'].to_list():
        theme_cluster_id = theme_df.loc[theme_df['description']==theme, property_name].iloc[0]
        result_list = theme_df.loc[theme_df[property_name]==theme_cluster_id, "description"].to_list()
    return result_list

In [440]:
def compare_gamma_for_theme(theme, gammas):
    column_names = [f"leidenGamma{gamma}" for gamma in gammas]
    lists = [get_cluster_for_theme(column, theme) for column in column_names]
    output_df = pd.DataFrame()
    output_df.loc[column_names[0], "final_themes"] = ", ".join(lists[0])
    for i in range(1, len(gammas)):
        output_df.loc[f"{column_names[i-1]} to {column_names[i]}", "dropped_themes"] = ", ".join([theme for theme in lists[i-1] if theme not in lists[i]])
        output_df.loc[f"{column_names[i-1]} to {column_names[i]}", "added_themes"] = ", ".join([theme for theme in lists[i] if theme not in lists[i-1]])
        output_df.loc[f"{column_names[i-1]} to {column_names[i]}", "final_themes"] = ", ".join(lists[i])
    return output_df

In [441]:
compare_gamma_for_theme("christmas", [32.0, 64.0, 128.0, 256.0, 512.0, 1024.0])

final_themes  \
leidenGamma32.0                        Christmas setting, Christmas Jam, Christmas World, Christmas magic, Christmas wedding, White Christmas, Christmas Variety, Christmas holidays, Christmas break, christmas, Christmas decorations, Navidad, Christmas celebration, Christmas celebrations, Christmas miracle, Christmas nightmare, Christmas curse, Christmas spirit, Christmas mystery, Christmas wish, Christmas wishes, Holiday traditions, Christmas memories, Christmas tradition, Christmas traditions, Christmas sweaters, Christmas lights, Christmas movie, Christmas eve, Christmas party, Christmas story, spicy Christmas, Xmas, Christmas ambience, Christmas terror, Christmas love, Christmas tragedy, Christmas proposal, Christmas gift, Christmas reunion, Family Christmas, Christmas competition, Christmas market, Santa competition, Christmas ornaments, Christmas tree, Christmas trees, Christmas train, Christmas songs, Christmas Eve wedding, Carol of the Bells, Christmas carols, Caroling, carols   
leidenGamma32.0 to leidenGamma64.0                                                                                                                                                                                                                                                                                 Christmas setting, Christmas Jam, Christmas World, Christmas magic, Christmas wedding, White Christmas, Christmas Variety, Christmas holidays, Christmas break, christmas, Navidad, Christmas celebration, Christmas celebrations, Christmas miracle, Christmas nightmare, Christmas curse, Christmas spirit, Christmas mystery, Christmas wish, Christmas wishes, Christmas sweaters, Christmas movie, Christmas eve, Christmas party, Christmas story, spicy Christmas, Xmas, Christmas ambience, Christmas terror, Christmas love, Christmas tragedy, Christmas proposal, Christmas gift, Christmas reunion, Family Christmas, Christmas competition, Christmas market, Santa competition, Christmas Eve wedding   
leidenGamma64.0 to leidenGamma128.0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Christmas holidays, Christmas break, christmas, Navidad, Xmas   
leidenGamma128.0 to leidenGamma256.0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Christmas ma

In [460]:
compare_gamma_for_theme("Christmas eve", [32.0, 64.0, 128.0, 256.0, 512.0, 1024.0])

final_themes  \
leidenGamma32.0                        Christmas setting, Christmas Jam, Christmas World, Christmas magic, Christmas wedding, White Christmas, Christmas Variety, Christmas holidays, Christmas break, christmas, Christmas decorations, Navidad, Christmas celebration, Christmas celebrations, Christmas miracle, Christmas nightmare, Christmas curse, Christmas spirit, Christmas mystery, Christmas wish, Christmas wishes, Holiday traditions, Christmas memories, Christmas tradition, Christmas traditions, Christmas sweaters, Christmas lights, Christmas movie, Christmas eve, Christmas party, Christmas story, spicy Christmas, Xmas, Christmas ambience, Christmas terror, Christmas love, Christmas tragedy, Christmas proposal, Christmas gift, Christmas reunion, Family Christmas, Christmas competition, Christmas market, Santa competition, Christmas ornaments, Christmas tree, Christmas trees, Christmas train, Christmas songs, Christmas Eve wedding, Carol of the Bells, Christmas carols, Caroling, carols   
leidenGamma32.0 to leidenGamma64.0                                                                                                                                                                                                                                                                                 Christmas setting, Christmas Jam, Christmas World, Christmas magic, Christmas wedding, White Christmas, Christmas Variety, Christmas holidays, Christmas break, christmas, Navidad, Christmas celebration, Christmas celebrations, Christmas miracle, Christmas nightmare, Christmas curse, Christmas spirit, Christmas mystery, Christmas wish, Christmas wishes, Christmas sweaters, Christmas movie, Christmas eve, Christmas party, Christmas story, spicy Christmas, Xmas, Christmas ambience, Christmas terror, Christmas love, Christmas tragedy, Christmas proposal, Christmas gift, Christmas reunion, Family Christmas, Christmas competition, Christmas market, Santa competition, Christmas Eve wedding   
leidenGamma64.0 to leidenGamma128.0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Christmas setting, Christmas World, Christmas wedding, White Christmas, Christmas celebration, Christmas celebrations, Christmas movie, Christmas eve, Christmas party, Christmas reunion, Family Christmas, Christmas competition, Christmas market, Santa competition, Christmas Eve wedding   
leidenGamma128.0 to leidenGamma256.0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Christmas wedding, Christmas eve, Christmas party, Family Christmas, Christmas competition, Christmas market, Santa competition, C

In [442]:
compare_gamma_for_theme("Beatles", [32.0, 64.0, 128.0, 256.0, 512.0, 1024.0])

final_themes dropped_themes  \
leidenGamma32.0                        Beatles, Paul McCartney            NaN   
leidenGamma32.0 to leidenGamma64.0     Beatles, Paul McCartney                  
leidenGamma64.0 to leidenGamma128.0    Beatles, Paul McCartney                  
leidenGamma128.0 to leidenGamma256.0   Beatles, Paul McCartney                  
leidenGamma256.0 to leidenGamma512.0   Beatles, Paul McCartney                  
leidenGamma512.0 to leidenGamma1024.0  Beatles, Paul McCartney                  

                                      added_themes  
leidenGamma32.0                                NaN  
leidenGamma32.0 to leidenGamma64.0                  
leidenGamma64.0 to leidenGamma128.0                 
leidenGamma128.0 to leidenGamma256.0                
leidenGamma256.0 to leidenGamma512.0                
leidenGamma512.0 to leidenGamma1024.0

In [443]:
compare_gamma_for_theme("soldier", [32.0, 64.0, 128.0, 256.0, 512.0, 1024.0])

final_themes dropped_themes added_themes
leidenGamma32.0                            soldier            NaN          NaN
leidenGamma32.0 to leidenGamma64.0         soldier                            
leidenGamma64.0 to leidenGamma128.0        soldier                            
leidenGamma128.0 to leidenGamma256.0       soldier                            
leidenGamma256.0 to leidenGamma512.0       soldier                            
leidenGamma512.0 to leidenGamma1024.0      soldier

In [444]:
compare_gamma_for_theme("Family bond", [32.0, 64.0, 128.0, 256.0, 512.0, 1024.0])

final_themes dropped_themes added_themes
leidenGamma32.0                        Family bond            NaN          NaN
leidenGamma32.0 to leidenGamma64.0     Family bond                            
leidenGamma64.0 to leidenGamma128.0    Family bond                            
leidenGamma128.0 to leidenGamma256.0   Family bond                            
leidenGamma256.0 to leidenGamma512.0   Family bond                            
leidenGamma512.0 to leidenGamma1024.0  Family bond

In [445]:
compare_gamma_for_theme("dark place", [32.0, 64.0, 128.0, 256.0, 512.0, 1024.0])

final_themes  \
leidenGamma32.0                        Darkness to light, Dark Power, dark journey, darkness vs. light, Blue thoughts, dark cracks, dark characters, Dark Void, darkest times, lights out, lost light, black void, Darkest Hour, Dark Fantasy, dark fantasies, dust, Dustlight, Dark Light, dark themes, dark self, Dark love, Dark interest, Dark realm, Dark legacy, Dark companion, dark child, inner darkness, dark place, out of darkness, Darkness beneath, dark world, Darkness and silence, Darkness within, dark abyss, divine darkness, dark, darkness, dark energy, dark presence, dark magic, dark force, dark forces, Deathful power, dark house, Dark Cost, dark vision, Dark Haven, dark manipulation, dark twist, Dark Figure, dark web, Dark ritual, dark network, Dark tale, Dark Prison, dark path, sinister world, Dark Highway, Dark forests, dark forest, dark road, dark thoughts, Deep dark, dark side, dark turn, dark time, dark corridors, dark city, dark room, dark office, dark stranger, dark holes, dark tunnel, dark walls, dark plot, dark scheme, dark cloud, dark clouds   
leidenGamma32.0 to leidenGamma64.0                                                                                                                                                                                                                                                                                                                                                   Darkness to light, dark journey, darkness vs. light, Blue thoughts, dark cracks, Dark Void, darkest times, black void, Darkest Hour, Dark Fantasy, dark fantasies, dark themes, Dark realm, inner darkness, dark place, out of darkness, Darkness beneath, dark world, Darkness and silence, Darkness within, dark abyss, divine darkness, dark, darkness, dark house, Dark Haven, dark twist, dark web, Dark ritual, dark network, Dark tale, Dark Prison, dark path, sinister world, Dark Highway, Dark forests, dark forest, dark road, dark thoughts, Deep dark, dark turn, dark time, dark corridors, dark city, dark room, dark office, dark holes, dark tunnel, dark walls, dark scheme, dark cloud, dark clouds   
leidenGamma64.0 to leidenGamma128.0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                dark journey, darkness vs. light, Blue thoughts, dark cracks, darkest times, Darkest Hour, Dark Fantasy, dark fantasies, dark themes, Dark realm, dark place, dark world, dark, darkness, dark house, Dark Haven, dark twist, dark web, Dark ritual, dark network, Dark tale, dark path, sinister world, Dark Highway, Dark forests, dark forest, dark road, dark thoughts, Deep dark, dark turn, dark time, dark corridors, dark city, dark room, dark office, dark holes, dark tunnel, dark walls, dark scheme, dark cloud, dark clouds   
leidenGamma128.0 to leidenGamma256.0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

In [446]:
compare_gamma_for_theme("horror comedy", [32.0, 64.0, 128.0, 256.0, 512.0, 1024.0])

final_themes  \
leidenGamma32.0                        Horror-Noir, survival horror, horror convention, Creepshow, Creeper, Zombie bite, gothic horror, horror genre, fantastical horror, Found footage horror, horror realm, noir, Human decomposition, Horror games, horror videos, Horror homage, horror stories, horror story, teen horror, J-horror, family horror, Real horror, zombie horror, silent horror, body horror, Turkish horror, horror footage, family terror, B-horror, Holiday Horrors, Holiday horror, horror, horrors, Horror filming, horror film, horror films, Horror movies, horror movie, Horror reboot, Horror series, horror franchise, Horror classic, horror classics, psycho-horror, horror-comedy, horror compilation, horror comedy, Horror icons, Horror elements, Horror villains, Horror legend, horror legends, Bodily horror, Creeping horror, Basement horror, Horror setting, horror anthology   
leidenGamma32.0 to leidenGamma64.0                      Horror-Noir, horror convention, Creepshow, Creeper, Zombie bite, gothic horror, horror genre, fantastical horror, Found footage horror, horror realm, noir, Human decomposition, Horror games, horror videos, Horror homage, horror stories, horror story, teen horror, J-horror, family horror, Real horror, zombie horror, silent horror, body horror, Turkish horror, horror footage, family terror, B-horror, Holiday Horrors, Holiday horror, horror, horrors, Horror filming, horror film, horror films, Horror movies, horror movie, Horror reboot, Horror series, horror franchise, Horror classic, horror classics, psycho-horror, horror-comedy, horror compilation, horror comedy, Horror icons, Horror elements, Horror villains, Horror legend, horror legends, Bodily horror, Creeping horror, Basement horror, Horror setting, horror anthology   
leidenGamma64.0 to leidenGamma128.0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Horror-Noir, gothic horror, fantastical horror, noir, J-horror, B-horror, psycho-horror, horror-comedy, horror compilation, horror comedy, horror anthology   
leidenGamma128.0 to leidenGamma256.0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                horror-comedy, horror compilation, horror comedy, horror anthology   
leidenGamma256.0 to leidenGamma512.0                                                                                                                                                                                                                                                                                                                                                                                                    

In [447]:
compare_gamma_for_theme("LGBTQ+", [32.0, 64.0, 128.0, 256.0, 512.0, 1024.0])

final_themes  \
leidenGamma32.0                        LGBT refugees, LGBTQ+ Iran, 2SLGBTQ+, LGBTQ pride, LGBTQI+ families, LGBTQIAP+, LGBTQ2IA+, LGBTQ+ pageant, Beauty pageants, beauty pageant, LGBTQ history, LGBTQ+, LGBT, LGBT youth, LGBTQ, LGBTQIA+, LGBT community, LGBTQ identity, LGBTQ+ identity, LGBTQ visibility, LGBTQ+ community, LGBTQ community, LGBTQIA+ community, LGBTQI+ community, LGBT+ acceptance, LGBTQ inclusion, LGBTQ+ archive, LGBT activism, queer activism, LGBTQIA+ activism, LGBTQ activism, LGBTQ discrimination, LGBTIQ+ migration   
leidenGamma32.0 to leidenGamma64.0                                                                                                         LGBTQ+ Iran, 2SLGBTQ+, LGBTQ pride, LGBTQI+ families, LGBTQIAP+, LGBTQ2IA+, LGBTQ+ pageant, Beauty pageants, beauty pageant, LGBTQ history, LGBTQ+, LGBT, LGBT youth, LGBTQ, LGBTQIA+, LGBT community, LGBTQ identity, LGBTQ+ identity, LGBTQ visibility, LGBTQ+ community, LGBTQ community, LGBTQIA+ community, LGBTQI+ community, LGBT+ acceptance, LGBTQ inclusion, LGBTQ+ archive, LGBTQ discrimination   
leidenGamma64.0 to leidenGamma128.0                                                                                                                                                                                                                                      LGBTQ+ Iran, 2SLGBTQ+, LGBTQ pride, LGBTQIAP+, LGBTQ2IA+, LGBTQ+ pageant, Beauty pageants, beauty pageant, LGBTQ history, LGBTQ+, LGBT, LGBT youth, LGBTQ, LGBTQIA+, LGBTQ identity, LGBTQ+ identity, LGBTQ visibility, LGBTQ inclusion, LGBTQ+ archive, LGBTQ discrimination   
leidenGamma128.0 to leidenGamma256.0                                                                                                                                                                                                                                                                                                                                                                                                                                                                               LGBTQ+, LGBTQ+ archive, LGBTQ+ Iran   
leidenGamma256.0 to leidenGamma512.0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               LGBTQ+, LGBTQ+ Iran   
leidenGamma512.0 to leidenGamma1024.0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              LGBTQ+ Iran, LGBTQ+   

                                                                                                                                                                                                                                                                 dropped_themes  \
leidenGamma32.0                                                                                                                                                                                                                                                             NaN   
leidenGamma32.0 to leidenGamma64.0                                                                                                                                           LGBT refugees, LGBT activism, qu

In [451]:
compare_gamma_for_theme("friendship, friendships", [32.0, 64.0, 128.0, 256.0, 512.0, 1024.0])

final_themes  \
leidenGamma32.0                        friendship adventure, friendship strain, Twisted friendship, misfit friendship, unlikely friendship, toxic friendship, strained friendship, unusual friendship, New friendships, unexpected friendship, Unlikely companionship, friendship test, friendship tested, enduring friendship, friend, friends, friendship unravels, friendships tested, friendship cracks, Friendly, female friendship, male friendship, Trans friendship, strong friendship, girl friendships, friendship, friendships, platonic friendship, friendship advice, Friendship dynamics, Friendship loyalty, friendship torn, Friendship bonds, friendship bond   
leidenGamma32.0 to leidenGamma64.0                                friendship adventure, friendship strain, Twisted friendship, misfit friendship, unlikely friendship, toxic friendship, strained friendship, unusual friendship, New friendships, unexpected friendship, Unlikely companionship, friendship test, friendship tested, enduring friendship, friendship unravels, friendships tested, friendship cracks, female friendship, male friendship, Trans friendship, strong friendship, girl friendships, friendship, friendships, platonic friendship, friendship advice, Friendship dynamics, Friendship loyalty, friendship torn, Friendship bonds, friendship bond   
leidenGamma64.0 to leidenGamma128.0                                                                                                                                                                                                                      friendship adventure, friendship strain, New friendships, friendship test, friendship tested, enduring friendship, friendship unravels, friendships tested, friendship cracks, female friendship, male friendship, Trans friendship, strong friendship, girl friendships, friendship, friendships, platonic friendship, friendship advice, Friendship dynamics, Friendship loyalty, Friendship bonds, friendship bond   
leidenGamma128.0 to leidenGamma256.0                                                                                                                                                                                                                                                                                                                                                                                                                                                             female friendship, male friendship, Trans friendship, strong friendship, girl friendships, friendship, friendships, platonic friendship, New friendships, enduring friendship   
leidenGamma256.0 to leidenGamma512.0                                                                                                                                                                                                                                                                                                                                                                                                                                                          friendship, friendships, friendship advice, Friendship dynamics, Friendship loyalty, Friendship bonds, friendship bond, friendship adventure, friendship strain, New friendships   
leidenGamma512.0 to leidenGamma1024.0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 New friendships, friendship, friendships   

                                   

In [450]:
compare_gamma_for_theme("friend, friends", [32.0, 64.0, 128.0, 256.0, 512.0, 1024.0])

final_themes  \
leidenGamma32.0                        friendship adventure, friendship strain, Twisted friendship, misfit friendship, unlikely friendship, toxic friendship, strained friendship, unusual friendship, New friendships, unexpected friendship, Unlikely companionship, friendship test, friendship tested, enduring friendship, friend, friends, friendship unravels, friendships tested, friendship cracks, Friendly, female friendship, male friendship, Trans friendship, strong friendship, girl friendships, friendship, friendships, platonic friendship, friendship advice, Friendship dynamics, Friendship loyalty, friendship torn, Friendship bonds, friendship bond   
leidenGamma32.0 to leidenGamma64.0                                                                                                                                                                                                                                                                                                                                                                                                      dearest friend, best friend, best friends, lifelong friends, close friends, rich friends, ex-best friend, friend, friends, prestigious friends, Friendly, school friends, loyal friend, faithful friend, cherished friend, true friend   
leidenGamma64.0 to leidenGamma128.0                                                                                                                                                                                                                                                                                                                                                                                                     dearest friend, best friend, best friends, lifelong friends, close friends, rich friends, ex-best friend, friend, friends, prestigious friends, Friendly, school friends, loyal friend, faithful friend, cherished friend, true friend   
leidenGamma128.0 to leidenGamma256.0                                                                                                                                                                                                                                                                                                                                                                                                    school friends, loyal friend, faithful friend, cherished friend, true friend, dearest friend, best friend, best friends, lifelong friends, close friends, rich friends, ex-best friend, friend, friends, prestigious friends, Friendly   
leidenGamma256.0 to leidenGamma512.0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  school friends, best friend, best friends, lifelong friends, close friends, rich friends, ex-best friend, friend, friends, prestigious friends, Friendly   
leidenGamma512.0 to leidenGamma1024.0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                friend, friends, Friendly   

                                   

In [155]:
compare_gamma_for_theme("high school friends", [32.0, 64.0, 128.0, 256.0, 512.0, 1024.0])

final_themes  \
leidenGamma32.0                        Acquaintance, acquaintances, old acquaintances, best friend, best friends, faithful friend, true friend, ex-best friend, school friends, close friends, enemy, old enemy, enemy positions, Frenemy, Friends turned enemies, friend or foe, frenemies, friends-turned-foes, friend, Friendly, friends, friend group, high school friends, old enemies, old friend, old friends, rich friends, New friendships, reunited friends, Teenage friends   
leidenGamma32.0 to leidenGamma64.0     Teenage friends, Acquaintance, acquaintances, old acquaintances, best friend, best friends, faithful friend, true friend, ex-best friend, school friends, close friends, enemy, old enemy, enemy positions, Frenemy, Friends turned enemies, friend or foe, frenemies, friends-turned-foes, friend, Friendly, friends, friend group, high school friends, old enemies, old friend, old friends, rich friends, New friendships, reunited friends   
leidenGamma64.0 to leidenGamma128.0    Acquaintance, acquaintances, old acquaintances, best friend, best friends, faithful friend, true friend, ex-best friend, school friends, close friends, enemy, old enemy, enemy positions, Frenemy, Friends turned enemies, friend or foe, frenemies, friends-turned-foes, friend, Friendly, friends, friend group, high school friends, old enemies, old friend, old friends, rich friends, New friendships, reunited friends, Teenage friends   
leidenGamma128.0 to leidenGamma256.0                                                                                                                                                                                                                                                                        school friends, close friends, friend, Friendly, friends, friend group, high school friends, old friends, rich friends, New friendships, reunited friends, Teenage friends   
leidenGamma256.0 to leidenGamma512.0                                                                                                                                                                                                                                                                                school friends, close friends, friend group, high school friends, old friends, rich friends, New friendships, reunited friends, siblings reunited, Teenage friends   
leidenGamma512.0 to leidenGamma1024.0                                                                                                                                                                                                                                                                                                                                                                               high school friends, reunited friends, siblings, siblings reunited   

                                                                                                                                                                                                                                                                                            dropped_themes  \
leidenGamma32.0                                                                                                                                                                                                                                                                                        NaN   
leidenGamma32.0 to leidenGamma64.0                                                                                                                                                                                                                                                                           
leidenGamma64.0 to leidenGamma128.0                                                                                                                                                                                                      

In [452]:
compare_gamma_for_theme("old woman", [32.0, 64.0, 128.0, 256.0, 512.0, 1024.0])

final_themes  \
leidenGamma32.0                        old soldier, Care home, old maid, Older man, old widower, older men, Old Men, middle-aged man, Retired couple, Wise elder, Elder, Elders, Dorothy, young man, elders' passing, Maids, maid, home birth, Sixty-year-old women, elderly women, home care, elderly, old couple, old man, old woman, old lady, old guys, elderly woman, elderly gentleman, Elderly spinster, elderly aunt, elderly Dorothy, senior woman, Elderly patient, Elderly widow, elderly couple, elderly wrestler, elderly love, Elderly witch, elderly sisters, elderly man, elderly lady, elderly maid, elderly mother, elderly student, bedridden woman, older woman, elderly protagonist, Senior citizen, senior citizens, Elderly father, elderly disguise, Village elders, village elder, old age, senility, elderly life, ageing, aging, Elderly coach, Elderly daughter, elderly rebellion, elderly home, Elderly uncle, Elderly farmer, Elderly priest, Elderly guardian, elderly parent, old age home, elderly care, real elder, aging parents, Senior, seniors, Elderly companionship, Aged care, nursing home, nursing homes, retirement home, retirement homes   
leidenGamma32.0 to leidenGamma64.0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     old soldier, old maid, Older man, old widower, older men, Old Men, old couple, old man, old woman, old lady, old guys, senior woman, older woman   
leidenGamma64.0 to leidenGamma128.0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      old maid, Dorothy, Maids, maid, Sixty-year-old women, elderly women, old couple, old woman, old lady, elderly woman, elderly Dorothy, senior woman, elderly sisters, elderly lady, elderly maid, elderly student, bedridden woman, older woman   
leidenGamma128.0 to leidenGamma256.0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           

In [454]:
compare_gamma_for_theme("musician, musicians", [32.0, 64.0, 128.0, 256.0, 512.0, 1024.0])

final_themes  \
leidenGamma32.0                        acoustic guitar, air guitar, Music Students, Music student, maverick musician, Music fans, Era-defining artists, artistes locaux, street musician, Young performers, guitar player, Guitarist audition, guitarist, guitar virtuoso, guitar freaks, electric guitar, guitar, guitars, Street performances, street performer, street performers, up-and-coming artists, local artists, music artists, emerging talents, Singing lessons, contemporary artists, international artists, guitar craft, guitar lessons, Female artist, women artists, American musician, LA musician, cult musician, musician, musicians, Prominent artists, Old musician   
leidenGamma32.0 to leidenGamma64.0                                                                                                                                                                                                 Music Students, Music student, maverick musician, Music fans, Era-defining artists, artistes locaux, street musician, Young performers, Street performances, street performer, street performers, up-and-coming artists, local artists, music artists, emerging talents, contemporary artists, international artists, Female artist, women artists, American musician, LA musician, cult musician, musician, musicians, Prominent artists, Old musician   
leidenGamma64.0 to leidenGamma128.0                                                                                                                                                                                                Music Students, Music student, maverick musician, Music fans, Era-defining artists, artistes locaux, street musician, Young performers, Street performances, street performer, street performers, up-and-coming artists, local artists, music artists, emerging talents, contemporary artists, international artists, Female artist, women artists, American musician, LA musician, cult musician, musician, musicians, Prominent artists, Old musician   
leidenGamma128.0 to leidenGamma256.0                                                                                                                                                                                                                                                                                                                                                                                                                             Street performances, street performer, street performers, American musician, LA musician, cult musician, musician, musicians, Old musician, Music Students, Music student, maverick musician, Music fans, street musician   
leidenGamma256.0 to leidenGamma512.0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    American musician, LA musician, cult musician, musician, musicians, Old musician, Music Students, Music student, maverick musician   
leidenGamma512.0 to leidenGamma1024.0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Music Students, Music student, maverick musician, Music fans, American musician, LA musician, cult musician, m

In [456]:
compare_gamma_for_theme("horse, horses", [32.0, 64.0, 128.0, 256.0, 512.0, 1024.0])

final_themes  \
leidenGamma32.0                        horse dreams, horseback, real horse, horse, horses, Equestrian, white horses, pale white horse   
leidenGamma32.0 to leidenGamma64.0     horse dreams, horseback, real horse, horse, horses, Equestrian, white horses, pale white horse   
leidenGamma64.0 to leidenGamma128.0    horse dreams, horseback, real horse, horse, horses, Equestrian, white horses, pale white horse   
leidenGamma128.0 to leidenGamma256.0   horse dreams, horseback, real horse, horse, horses, Equestrian, white horses, pale white horse   
leidenGamma256.0 to leidenGamma512.0   horse dreams, horseback, real horse, horse, horses, Equestrian, white horses, pale white horse   
leidenGamma512.0 to leidenGamma1024.0  horse dreams, horseback, real horse, horse, horses, Equestrian, white horses, pale white horse   

                                      dropped_themes added_themes  
leidenGamma32.0                                  NaN          NaN  
leidenGamma32.0 to leidenGamma64.0                                 
leidenGamma64.0 to leidenGamma128.0                                
leidenGamma128.0 to leidenGamma256.0                               
leidenGamma256.0 to leidenGamma512.0                               
leidenGamma512.0 to leidenGamma1024.0

In [457]:
compare_gamma_for_theme("Starfish", [32.0, 64.0, 128.0, 256.0, 512.0, 1024.0])

final_themes dropped_themes added_themes
leidenGamma32.0                           Starfish            NaN          NaN
leidenGamma32.0 to leidenGamma64.0        Starfish                            
leidenGamma64.0 to leidenGamma128.0       Starfish                            
leidenGamma128.0 to leidenGamma256.0      Starfish                            
leidenGamma256.0 to leidenGamma512.0      Starfish                            
leidenGamma512.0 to leidenGamma1024.0     Starfish

# Write best Leiden communities to Neo4j
Based on the examples above, 256.0 seems like a good level for gamma.
Rename the property LeidenGamma32.0 from the graph projection to leidenId in the on-disk graph.
Drop any leidenId values from a previous run.

In [463]:
gds.run_cypher("MATCH (t:Theme|Stem) SET t.leidenId = null")
gds.graph.nodeProperties.write(g_themes2, {"leidenGamma512.0": "leidenId"})

writeMillis                       63
graphName            reweight_themes
nodeProperties            [leidenId]
propertiesWritten              19645
Name: 0, dtype: object

Create ThemeGroup nodes connecting themes that are duplicates.

In [464]:
gds.run_cypher("""CREATE CONSTRAINT theme_group_node_key IF NOT EXISTS FOR (n:ThemeGroup) REQUIRE n.id IS NODE KEY""")

Empty DataFrame
Columns: []
Index: []

In [472]:
gds.run_cypher("""
MATCH (t:Theme)
WHERE t.leidenId IS NOT NULL
WITH t ORDER BY t.description
WITH t.leidenId AS id, collect(t) AS themeNodes, collect(t.description) AS descriptions
MERGE (g:ThemeGroup {id:id}) 
SET g.descriptions = descriptions
WITH g, themeNodes
FOREACH (t in themeNodes | MERGE (t)-[:IN_GROUP]->(g))
""")

Empty DataFrame
Columns: []
Index: []

In [473]:
gds.run_cypher("""
MATCH (s:Stem)
WHERE s.leidenId IS NOT NULL
CALL
{
WITH s
MERGE (g:ThemeGroup {id:s.leidenId}) 
SET g.descriptions = coalesce(g.descriptions, []) + s.descriptions
WITH s, g
MATCH (s)<-[:HAS_STEM]-(t)
MERGE (t)-[:IN_GROUP]->(g)
}
""")

Empty DataFrame
Columns: []
Index: []

Create ThemeGroup nodes for Theme nodes that are not already grouped in a theme group if the theme is referenced in more than one document.

In [474]:
gds.run_cypher("""
MATCH (g:ThemeGroup)
WITH max(g.id) AS maxId
MATCH (t:Theme)
WHERE NOT EXISTS {(t)-[:IN_GROUP]->()}
AND COUNT {(t)<-[:HAS_THEME]-()}  > 1
WITH maxId, COLLECT(t) AS needsGroup
UNWIND range(0, size(needsGroup)-1) AS idx
WITH maxId, idx, needsGroup[idx] AS t
MERGE (g:ThemeGroup {id:maxId + idx + 1})
SET g.descriptions = [t.description]
WITH g, t
MERGE (t)-[:IN_GROUP]->(g)
RETURN COUNT(*) AS singleThemeGroups
""")

singleThemeGroups
0               2891

For Theme nodes that are not already in a theme group and contain only one document, create ThemeGroup nodes and add a simple summary.

In [512]:
single_doc_df = gds.run_cypher("""
    MATCH (g:ThemeGroup)
    WITH max(g.id) AS maxId
    MATCH (t:Theme) WHERE NOT EXISTS {(t)-[:IN_GROUP]->()} 
    WITH maxId, COLLECT(t) AS needsGroup
    UNWIND range(0, size(needsGroup)-1) AS idx
    WITH maxId, idx, needsGroup[idx] AS t
    CALL
    {
    WITH t, maxId, idx
    MERGE (g:ThemeGroup {id:maxId + idx + 1})
    SET g.descriptions = [t.description]
    SET g.summary = "A movie about " + t.description
    MERGE (t)-[:IN_GROUP]->(g)
    RETURN g
    } IN TRANSACTIONS OF 10000 ROWS
    RETURN g.id AS groupId, g.summary AS summary""")

In [513]:
embeddings = OpenAIEmbeddings(model="text-embedding-3-small", openai_api_key=openai_api_key)

In [514]:
single_doc_df['embedding'] = embeddings.embed_documents(single_doc_df['summary'].tolist())

In [515]:
gds.run_cypher("""
UNWIND $data AS row
CALL
{
WITH row
MATCH (g:ThemeGroup {id:row['groupId']})
CALL db.create.setNodeVectorProperty(g, 'summaryEmbedding', row['embedding'])
} IN TRANSACTIONS OF 10000 ROWS
""", {"data": single_doc_df[['groupId', 'embedding']].to_dict("records")})

Empty DataFrame
Columns: []
Index: []

# Clean up projections

In [479]:
gds.graph.drop(g_themes)

In [480]:
gds.graph.drop(g_themes2)

# Add mean vector representation to each ThemeGroup

In [482]:
group_embeddings_df = gds.run_cypher("""
MATCH (g:ThemeGroup)<-[:IN_GROUP]-(t)
RETURN g.id AS groupId, collect(t.embedding) AS embeddings
""")

In [483]:
group_embeddings_df['mean_embedding'] = group_embeddings_df.apply(get_mean_vector, axis=1)

In [484]:
gds.run_cypher("""
    UNWIND $data AS row
    MATCH (g:ThemeGroup {id: row['groupId']})
    CALL db.create.setNodeVectorProperty(g, "meanEmbedding", row['mean_embedding'])""",
                   {"data":group_embeddings_df[['groupId', 'mean_embedding']].to_dict("records")})


Empty DataFrame
Columns: []
Index: []

In [485]:
gds.run_cypher("""CREATE VECTOR INDEX theme_group_mean_vectors IF NOT EXISTS 
                  FOR (t:ThemeGroup)
                  ON (t.meanEmbedding)
                  OPTIONS {indexConfig: 
                      {`vector.dimensions`: 1536,
                       `vector.similarity_function`: 'cosine'
                       }}
                       """)

Empty DataFrame
Columns: []
Index: []